package com.sansim.app.util

import android.content.Context
import android.graphics.BitmapFactory
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.platform.LocalContext

object CardBackgroundLoader {
    // 国家代码到背景图片文件名的映射
    private val countryCodeToFile = mapOf(
        "AF" to "card-background-afghanistan-lighttrail.jpg",
        "AL" to "card-background-albania-lighttrail.jpg",
        "DZ" to "card-background-algeria-lighttrail.jpg",
        "AD" to "card-background-andorra-lighttrail.jpg",
        "AO" to "card-background-angola-lighttrail.jpg",
        "AG" to "card-background-antigua-barbuda-lighttrail.jpg",
        "AR" to "card-background-argentina-lighttrail.jpg",
        "AM" to "card-background-armenia-lighttrail.jpg",
        "AU" to "card-background-australia-lighttrail.jpg",
        "AT" to "card-background-austria-lighttrail.jpg",
        "AZ" to "card-background-azerbaijan-lighttrail.jpg",
        "BS" to "card-background-bahamas-lighttrail.jpg",
        "BH" to "card-background-bahrain-lighttrail.jpg",
        "BD" to "card-background-bangladesh-lighttrail.jpg",
        "BB" to "card-background-barbados-lighttrail.jpg",
        "BY" to "card-background-belarus-lighttrail.jpg",
        "BE" to "card-background-belgium-lighttrail.png",
        "BZ" to "card-background-belize-lighttrail.png",
        "BJ" to "card-background-benin-lighttrail.jpg",
        "BT" to "card-background-bhutan-lighttrail.jpg",
        "BO" to "card-background-bolivia-lighttrail.jpg",
        "BA" to "card-background-bosnia-herzegovina-lighttrail.jpg",
        "BW" to "card-background-botswana-lighttrail.jpg",
        "BR" to "card-background-brazil-lighttrail.jpg",
        "BN" to "card-background-brunei-lighttrail.png",
        "BG" to "card-background-bulgaria-lighttrail.png",
        "BF" to "card-background-burkina-faso-lighttrail.png",
        "BI" to "card-background-burundi-lighttrail.png",
        "CV" to "card-background-cape-verde-lighttrail.jpg",
        "KH" to "card-background-cambodia-lighttrail.png",
        "CM" to "card-background-cameroon-lighttrail.png",
        "CA" to "card-background-canada-lighttrail.png",
        "CF" to "card-background-central-african-republic-lighttrail.jpg",
        "TD" to "card-background-chad-lighttrail.jpg",
        "CL" to "card-background-chile-lighttrail.jpg",
        "CN" to "card-background-china-lighttrail.jpg",
        "CO" to "card-background-colombia-lighttrail.jpg",
        "KM" to "card-background-comoros-lighttrail.jpg",
        "CG" to "card-background-congo-brazzaville-lighttrail.jpg",
        "CD" to "card-background-congo-kinshasa-lighttrail.jpg",
        "CR" to "card-background-costa-rica-lighttrail.jpg",
        "CI" to "card-background-cote-divoire-lighttrail.jpg",
        "HR" to "card-background-croatia-lighttrail.jpg",
        "CU" to "card-background-cuba-lighttrail.jpg",
        "CY" to "card-background-cyprus-lighttrail.jpg",
        "CZ" to "card-background-czechia-lighttrail.jpg",
        "DK" to "card-background-denmark-lighttrail.jpg",
        "DJ" to "card-background-djibouti-lighttrail.jpg",
        "DM" to "card-background-dominica-lighttrail.jpg",
        "DO" to "card-background-dominican-republic-lighttrail.jpg",
        "EC" to "card-background-ecuador-lighttrail.jpg",
        "EG" to "card-background-egypt-lighttrail.jpg",
        "SV" to "card-background-el-salvador-lighttrail.jpg",
        "GQ" to "card-background-equatorial-guinea-lighttrail.jpg",
        "ER" to "card-background-eritrea-lighttrail.jpg",
        "EE" to "card-background-estonia-lighttrail.jpg",
        "SZ" to "card-background-eswatini-lighttrail.jpg",
        "ET" to "card-background-ethiopia-lighttrail.jpg",
        "FJ" to "card-background-fiji-lighttrail.jpg",
        "FI" to "card-background-finland-lighttrail.jpg",
        "FR" to "card-background-france-lighttrail.jpg",
        "GA" to "card-background-gabon-lighttrail.jpg",
        "GM" to "card-background-gambia-lighttrail.jpg",
        "GE" to "card-background-georgia-lighttrail.jpg",
        "DE" to "card-background-germany-lighttrail.jpg",
        "GH" to "card-background-ghana-lighttrail.jpg",
        "GR" to "card-background-greece-lighttrail.jpg",
        "GD" to "card-background-grenada-lighttrail.jpg",
        "GT" to "card-background-guatemala-lighttrail.jpg",
        "GN" to "card-background-guinea-lighttrail.jpg",
        "GW" to "card-background-guinea-bissau-lighttrail.jpg",
        "GY" to "card-background-guyana-lighttrail.jpg",
        "HT" to "card-background-haiti-lighttrail.jpg",
        "HN" to "card-background-honduras-lighttrail.jpg",
        "HK" to "card-background-hong-kong-lighttrail.jpg",
        "HU" to "card-background-hungary-lighttrail.jpg",
        "IS" to "card-background-iceland-lighttrail.jpg",
        "IN" to "card-background-india-lighttrail.jpg",
        "ID" to "card-background-indonesia-lighttrail.jpg",
        "IR" to "card-background-iran-lighttrail.jpg",
        "IQ" to "card-background-iraq-lighttrail.jpg",
        "IE" to "card-background-ireland-lighttrail.jpg",
        "IL" to "card-background-israel-lighttrail.jpg",
        "IT" to "card-background-italy-lighttrail.jpg",
        "JM" to "card-background-jamaica-lighttrail.jpg",
        "JP" to "card-background-japan-lighttrail.jpg",
        "JO" to "card-background-jordan-lighttrail.jpg",
        "KZ" to "card-background-kazakhstan-lighttrail.jpg",
        "KE" to "card-background-kenya-lighttrail.jpg",
        "KI" to "card-background-kiribati-lighttrail.jpg",
        "KP" to "card-background-north-korea-lighttrail.jpg",
        "KR" to "card-background-south-korea-lighttrail.jpg",
        "KW" to "card-background-kuwait-lighttrail.jpg",
        "KG" to "card-background-kyrgyzstan-lighttrail.jpg",
        "LA" to "card-background-laos-lighttrail.jpg",
        "LV" to "card-background-latvia-lighttrail.jpg",
        "LB" to "card-background-lebanon-lighttrail.jpg",
        "LS" to "card-background-lesotho-lighttrail.jpg",
        "LR" to "card-background-liberia-lighttrail.jpg",
        "LY" to "card-background-libya-lighttrail.jpg",
        "LI" to "card-background-liechtenstein-lighttrail.jpg",
        "LT" to "card-background-lithuania-lighttrail.jpg",
        "LU" to "card-background-luxembourg-lighttrail.jpg",
        "MO" to "card-background-macau-lighttrail.jpg",
        "MG" to "card-background-madagascar-lighttrail.jpg",
        "MW" to "card-background-malawi-lighttrail.jpg",
        "MY" to "card-background-malaysia-lighttrail.jpg",
        "MV" to "card-background-maldives-lighttrail.jpg",
        "ML" to "card-background-mali-lighttrail.jpg",
        "MT" to "card-background-malta-lighttrail.jpg",
        "MH" to "card-background-marshall-islands-lighttrail.jpg",
        "MR" to "card-background-mauritania-lighttrail.jpg",
        "MU" to "card-background-mauritius-lighttrail.jpg",
        "MX" to "card-background-mexico-lighttrail.jpg",
        "FM" to "card-background-micronesia-lighttrail.jpg",
        "MD" to "card-background-moldova-lighttrail.jpg",
        "MC" to "card-background-monaco-lighttrail.jpg",
        "MN" to "card-background-mongolia-lighttrail.jpg",
        "ME" to "card-background-montenegro-lighttrail.jpg",
        "MA" to "card-background-morocco-lighttrail.jpg",
        "MZ" to "card-background-mozambique-lighttrail.jpg",
        "MM" to "card-background-myanmar-lighttrail.jpg",
        "NA" to "card-background-namibia-lighttrail.jpg",
        "NR" to "card-background-nauru-lighttrail.jpg",
        "NP" to "card-background-nepal-lighttrail.jpg",
        "NL" to "card-background-netherlands-lighttrail.jpg",
        "NZ" to "card-background-new-zealand-lighttrail.jpg",
        "NI" to "card-background-nicaragua-lighttrail.jpg",
        "NE" to "card-background-niger-lighttrail.jpg",
        "NG" to "card-background-nigeria-lighttrail.jpg",
        "NO" to "card-background-norway-lighttrail.jpg",
        "OM" to "card-background-oman-lighttrail.jpg",
        "PK" to "card-background-pakistan-lighttrail.jpg",
        "PW" to "card-background-palau-lighttrail.jpg",
        "PA" to "card-background-panama-lighttrail.jpg",
        "PG" to "card-background-papua-new-guinea-lighttrail.jpg",
        "PY" to "card-background-paraguay-lighttrail.jpg",
        "PE" to "card-background-peru-lighttrail.jpg",
        "PH" to "card-background-philippines-lighttrail.jpg",
        "PL" to "card-background-poland-lighttrail.jpg",
        "PT" to "card-background-portugal-lighttrail.jpg",
        "QA" to "card-background-qatar-lighttrail.jpg",
        "RO" to "card-background-romania-lighttrail.jpg",
        "RU" to "card-background-russia-lighttrail.jpg",
        "RW" to "card-background-rwanda-lighttrail.jpg",
        "KN" to "card-background-saint-kitts-and-nevis-lighttrail.jpg",
        "LC" to "card-background-saint-lucia-lighttrail.jpg",
        "VC" to "card-background-saint-vincent-and-the-grenadines-lighttrail.jpg",
        "WS" to "card-background-samoa-lighttrail.jpg",
        "SM" to "card-background-san-marino-lighttrail.jpg",
        "ST" to "card-background-sao-tome-and-principe-lighttrail.jpg",
        "SA" to "card-background-saudi-arabia-lighttrail.jpg",
        "SN" to "card-background-senegal-lighttrail.jpg",
        "RS" to "card-background-serbia-lighttrail.jpg",
        "SC" to "card-background-seychelles-lighttrail.jpg",
        "SL" to "card-background-sierra-leone-lighttrail.jpg",
        "SG" to "card-background-singapore-lighttrail.jpg",
        "SK" to "card-background-slovakia-lighttrail.jpg",
        "SI" to "card-background-slovenia-lighttrail.jpg",
        "SB" to "card-background-solomon-islands-lighttrail.jpg",
        "SO" to "card-background-somalia-lighttrail.jpg",
        "ZA" to "card-background-south-africa-lighttrail.jpg",
        "SS" to "card-background-south-sudan-lighttrail.jpg",
        "ES" to "card-background-spain-lighttrail.jpg",
        "LK" to "card-background-sri-lanka-lighttrail.jpg",
        "SD" to "card-background-sudan-lighttrail.jpg",
        "SR" to "card-background-suriname-lighttrail.jpg",
        "SE" to "card-background-sweden-lighttrail.jpg",
        "CH" to "card-background-switzerland-lighttrail.jpg",
        "SY" to "card-background-syria-lighttrail.jpg",
        "TW" to "card-background-taiwan-lighttrail.jpg",
        "TJ" to "card-background-tajikistan-lighttrail.jpg",
        "TZ" to "card-background-tanzania-lighttrail.jpg",
        "TH" to "card-background-thailand-lighttrail.jpg",
        "TL" to "card-background-timor-leste-lighttrail.jpg",
        "TG" to "card-background-togo-lighttrail.jpg",
        "TO" to "card-background-tonga-lighttrail.jpg",
        "TT" to "card-background-trinidad-and-tobago-lighttrail.jpg",
        "TN" to "card-background-tunisia-lighttrail.jpg",
        "TR" to "card-background-turkey-lighttrail.jpg",
        "TM" to "card-background-turkmenistan-lighttrail.jpg",
        "TV" to "card-background-tuvalu-lighttrail.jpg",
        "UG" to "card-background-uganda-lighttrail.jpg",
        "UA" to "card-background-ukraine-lighttrail.jpg",
        "AE" to "card-background-united-arab-emirates-lighttrail.jpg",
        "GB" to "card-background-united-kingdom-lighttrail.jpg",
        "US" to "card-background-united-states-lighttrail.jpg",
        "UY" to "card-background-uruguay-lighttrail.jpg",
        "UZ" to "card-background-uzbekistan-lighttrail.jpg",
        "VU" to "card-background-vanuatu-lighttrail.jpg",
        "VA" to "card-background-vatican-city-lighttrail.jpg",
        "VE" to "card-background-venezuela-lighttrail.jpg",
        "VN" to "card-background-vietnam-lighttrail.jpg",
        "YE" to "card-background-yemen-lighttrail.jpg",
        "ZM" to "card-background-zambia-lighttrail.jpg",
        "ZW" to "card-background-zimbabwe-lighttrail.jpg"
    )
    
    fun getCardBackgroundFileName(countryCode: String): String? {
        return countryCodeToFile[countryCode.uppercase()]
    }
    
    fun loadCardBackground(context: Context, countryCode: String): ImageBitmap? {
        val fileName = getCardBackgroundFileName(countryCode) ?: return null
        return try {
            val inputStream = context.assets.open("card_backgrounds/")
            val bitmap = BitmapFactory.decodeStream(inputStream)
            inputStream.close()
            bitmap?.asImageBitmap()
        } catch (e: Exception) {
            null
        }
    }
}

@Composable
fun rememberCardBackground(countryCode: String): ImageBitmap? {
    val context = LocalContext.current
    return remember(countryCode) {
        CardBackgroundLoader.loadCardBackground(context, countryCode)
    }
}
